#!/usr/bin/env python3
# vim: ts=4 sw=4 sts=4 et ai

import os, sys
import time

ltime = time.localtime()
dirname = os.path.join('content', 'posts', f'{ltime.tm_year}', f'{ltime.tm_mon:02d}')
if not os.path.exists(dirname):
    os.makedirs(dirname)

basename = sys.argv[1]
filename = os.path.join(dirname, basename + '.md')
with open(filename, 'w') as fp:
    fp.write('Title:\n')
    fp.write(f'Slug: {ltime.tm_year}_{ltime.tm_mon:02d}_{ltime.tm_mday:02d}_' + basename.replace('-', '_') + '\n')
    fp.write(f'Date: {ltime.tm_year}-{ltime.tm_mon:02d}-{ltime.tm_mday:02d} {ltime.tm_hour:02d}:{ltime.tm_min:02d}\n')
    fp.write('Category: tech\n')
    fp.write('Tag: \n')
    fp.write('Summary: \n')
    fp.write('\n')

cmd = 'atom', filename
os.execlp(cmd[0], *cmd)
